---
title: "Traditional Methods 207 Final Project"
author: "Dylan Chou, Tim Yao"
date: "2024-05-30"
output: pdf_document
---

```{r, include=F}
library(astsa)
library(tseries)
library(forecast)
library(aTSA)
library(KFAS)
library(mgcv)
library(bayesforecast)
```

## Two Time Series Plots of Electricity and Weather

```{r}
# par(mfrow=c(2,2))
etth1 = read.csv("./data/ETTh1.csv")
etth2 = read.csv("./data/ETTh2.csv")
ettm1 = read.csv("./data/ETTm1.csv")
weather = read.csv("./data/WTH.csv")
aeph = read.csv("./data/AEP_hourly.csv")


# univariate time series
# https://stackoverflow.com/questions/33782218/how-to-create-a-time-series-of-hourly-data
first_hour_etth1 = 24*(as.Date("2016-07-01 00:00:00")-as.Date("2016-1-1 00:00:00"))
etth1.ts.original = ts(data=etth1$OT, start=c(2016, first_hour_etth1), freq=24*365)

etth1.ts = (etth1.ts.original-mean(etth1.ts.original))/sd(etth1.ts.original)

etth2.ts.original = ts(data=etth2$OT, start=c(2016, first_hour_etth1), freq=24*365)
etth2.ts = (etth2.ts.original-mean(etth2.ts.original))/sd(etth2.ts.original)

# ettm1

ettm1.ts.original = ts(data=ettm1$OT, start=c(2016, first_hour_etth1), freq=4*24*365)
ettm1.ts = (ettm1.ts.original-mean(ettm1.ts.original))/sd(ettm1.ts.original)


weather.ts.original = ts(data=weather$WetBulbCelsius, start=c(2010, 0), freq=24*365)
weather.ts = (weather.ts.original-mean(weather.ts.original))/sd(weather.ts.original)


first_hour_aeph = 24*(as.Date("2004-12-31 01:00:00")-as.Date("2004-1-1 00:00:00"))
aeph.ts.original = ts(data=aeph$AEP_MW, start=c(2004, first_hour_aeph), freq=24*365)
aeph.ts = (aeph.ts.original-mean(aeph.ts.original))/sd(aeph.ts.original)

plot(etth1.ts.original, main="ETTH1 Electricity Oil Temperature", ylab="Oil Temperature (Celsius)")
plot(etth2.ts.original, main="ETTH2 Electricity Oil Temperature", ylab="Oil Temperature (Celsius)")
plot(ettm1.ts.original, main="ETTM1 Electricity Oil Temperature", ylab="Oil Temperature (Celsius)")
plot(weather.ts.original, main="Weather Wet Bulb Temperature (Celsius)", ylab="Wet Bulb Temperature (Celsius)")
plot(aeph.ts.original, main="AEPh Megawatt Energy Consumption",ylab="Megawatt Energy Consumption")
```

## Autocorrelation of current time series

```{r}
# original data can't be operated on directly due to slow decrease in acf across lags
par(mfrow=c(2,2))
# first diagnose the autocorrelation of the existing time series
acf(etth1.ts, lag.max=200)
acf(etth2.ts, lag.max=200)
acf(ettm1.ts, lag.max=200)
acf(weather.ts, lag.max=200)
acf(aeph.ts, lag.max=2000)
```

```{r}
gen_plots = function(dataset=etth1.ts, freq=24*365) {
  par(mfrow=c(2,4))
  curr_time = time(dataset)
  reg1 = lm(dataset~curr_time+I(curr_time^3))
  
  plot(dataset)
  points(curr_time, predict.lm(reg1),type='l',col='blue')
  
  seasonality = dataset-predict.lm(reg1)
  
  f1 = 1
  f2 = 3
  f3 = 12
  d = freq
  v1 = cos(2*base::pi*f1*(1:length(dataset))/d)
  v2 = sin(2*base::pi*f1*(1:length(dataset))/d)
  v3 = cos(2*base::pi*f2*(1:length(dataset))/d)
  v4 = sin(2*base::pi*f2*(1:length(dataset))/d)
  v5 = cos(2*base::pi*f3*(1:length(dataset))/d)
  v6 = sin(2*base::pi*f3*(1:length(dataset))/d)
  
  seasonal_fit1 = lm(seasonality ~ 1 + v1 + v2 + v3 + v4)
  plot(1:length(dataset), seasonality, type="l")
  points(1:length(dataset), seasonal_fit1$fitted, type = "l", col = "firebrick",lwd=3)
  after_trend_seasonality_dataset = seasonality-seasonal_fit1$fitted
  acf(after_trend_seasonality_dataset,lag.max=200)
  kpss.test(after_trend_seasonality_dataset)
  return(after_trend_seasonality_dataset)
}
etth1.ts.residuals = gen_plots(etth1.ts)
etth2.ts.residuals = gen_plots(etth2.ts)
ettm1.ts.residuals = gen_plots(ettm1.ts, freq=24*365*4)
weather.ts.residuals = gen_plots(weather.ts)
aeph.ts.residuals = gen_plots(aeph.ts)

```





## Differencing - trend elimination

```{r}
# etth1
acf(diff(diff(etth1.ts,lag=1), lag=1), lag.max=200)
acf(diff(etth1.ts,lag=24), lag.max=200)
acf(diff(diff(etth1.ts,lag=24)), lag.max=200)
acf(diff(etth1.ts,lag=24*2), lag.max=200)
acf(diff(etth1.ts,lag=4), lag.max=200)

kpss.test(diff(diff(etth1.ts), lag=24))
adf.test(diff(etth1.ts,lag=24))


# etth2
acf(diff(diff(etth2.ts,lag=1), lag=1), lag.max=200)
acf(diff(etth2.ts,lag=24), lag.max=200)
acf(diff(diff(etth2.ts,lag=24)), lag.max=200)

adf.test(diff(diff(etth2.ts,lag=24)))
kpss.test(diff(diff(etth2.ts,lag=24)))

# ettm1
acf(diff(diff(ettm1.ts,lag=4*12)), lag.max=200)
acf(diff(ettm1.ts,lag=4), lag.max=200)
acf(diff(ettm1.ts,lag=4*12), lag.max=200)

# we consider the longer periods in ettm1 as the 
# resulting time series is stationary and
# may be able to capture patterns
# and variance of the data better.
adf.test(diff(ettm1.ts, lag=4*12))
kpss.test(diff(ettm1.ts, lag=4*12))

# Weather 
acf(diff(diff(weather.ts),lag=24),lag.max=200)
kpss.test(diff(weather.ts, lag=24))
adf.test(diff(weather.ts, lag=24))

# Aeph
acf(diff(aeph.ts,lag=24), lag.max=200)
acf(diff(aeph.ts,lag=24*2), lag.max=200)

kpss.test(diff(aeph.ts, lag=24*2))
kpss.test(diff(aeph.ts, lag=24))
kpss.test(aeph.ts)

adf.test(diff(aeph.ts, lag=24*2))
adf.test(diff(aeph.ts, lag=24))

# on residual datasets

# etth1.ts
acf(diff(diff(etth1.ts), lag=24),lag.max=200)
acf(diff(etth1.ts.residuals),lag.max=200)

kpss.test(diff(diff(etth1.ts.residuals), lag=24))
adf.test(diff(etth1.ts.residuals,lag=24))

# etth2.ts
acf(diff(diff(etth2.ts.residuals,lag=24)), lag.max=200)

adf.test(diff(diff(etth2.ts.residuals,lag=24)))
kpss.test(diff(diff(etth2.ts.residuals,lag=24)))

# ettm1.ts
acf(diff(ettm1.ts.residuals,lag=4*12), lag.max=200)

# we consider the longer periods in ettm1 as the 
# resulting time series is stationary and
# may be able to capture patterns
# and variance of the data better.
adf.test(diff(ettm1.ts.residuals, lag=4*12))
kpss.test(diff(ettm1.ts.residuals, lag=4*12))

# weather
acf(diff(weather.ts.residuals,lag=24),lag.max=200)
kpss.test(diff(weather.ts.residuals, lag=24))
adf.test(diff(weather.ts.residuals, lag=24))

# aeph
acf(diff(aeph.ts.residuals,lag=24*2), lag.max=200)
kpss.test(diff(aeph.ts.residuals, lag=24*2))
adf.test(diff(aeph.ts.residuals, lag=24*2))

```

## Trying different models based on preliminary plots

```{r}
# ETTH1
# Ideal to difference twice to remove trend. Estimates using CSS-ML

grid_search_cv = function(dataset, ar_range, ma_range, diff_range, periods, seasonal_ma_range, 
                          seasonal_ar_range, pred_lens, n_folds, non_oos_prop,
                          first_year, first_val, dataset_freq) {
  if (n_folds <= 1) {
    stop("Not enough folds")
  }
  
  # OUTPUT
  results = list()
  
  non_oos_size = length(dataset)*non_oos_prop
  non_oos = ts(dataset[1:non_oos_size], start=c(first_year, first_val), freq=dataset_freq)
  chunk_length = as.integer(non_oos_size/n_folds)
  
  for (pred_len in pred_lens) {
    print(paste("Outer Loop prediction length:", pred_len))
    for (fold in 1:(n_folds-1)) {
      train_start = chunk_length*(fold-1)+1
      train_end = fold*chunk_length-1
      
      validation_start = train_end + 1
      if (fold == (n_folds-1)) {
        validation_end = non_oos_size
      } else {
        validation_end = (fold+1)*chunk_length-1
      }
      train = non_oos[train_start:train_end]
      validation = non_oos[validation_start:validation_end]
      for (ar_comp in ar_range) {
        for (ma_comp in ma_range) {
          for (diff in diff_range) {
            print(paste("Current components: ", ar_comp, ",", diff, ",", ma_comp, " - fold: ", fold, sep=""))
            for (curr_period in periods) {
              for (seasonal_ma in seasonal_ma_range) {
                for (seasonal_ar in seasonal_ar_range) {
                  result <- tryCatch({
                    temp_model = arima(train, order = c(ar_comp,diff,ma_comp),
                                     seasonal=list(order=c(seasonal_ar,1,seasonal_ma), 
                                                   period=curr_period))
                      list(success = TRUE, temp_model = temp_model)
                    }, error = function(e) {
                      message("ARIMA(", paste(ar_comp,diff,ma_comp, collapse = ","), ") failed: ", e$message)
                      list(success = FALSE, temp_model = NULL)
                    })
                  if (!result$success) {
                    next
                  }
                  
                  pred_call = predict(temp_model, n.ahead=pred_len)
                  curr_pred = pred_call$pred
                  mse = mean( (validation[1:pred_len]-curr_pred)^2 )
                  mae = mean( abs(validation[1:pred_len]-curr_pred) )
                  
                  results[[paste("(",ar_comp,",",diff,",",ma_comp, ",",seasonal_ar,",1,",
                                 seasonal_ma,", curr_period:", 
                                 curr_period,", prediction length:" ,
                                 pred_len, " MSE", sep="")]] =
                    c(results[[paste("(",ar_comp,",",diff,",",ma_comp, ",",seasonal_ar,",1,",
                                 seasonal_ma,", curr_period:", 
                                 curr_period,", prediction length:" ,
                                 pred_len, " MSE", sep="")]], mse)
                  results[[paste("(",ar_comp,",",diff,",",ma_comp, ",",seasonal_ar,",1,",
                                 seasonal_ma,", curr_period:", 
                                 curr_period,", prediction length:" ,
                                 pred_len, " MAE", sep="")]] =
                    c(results[[paste("(",ar_comp,",",diff,",",ma_comp, ",",seasonal_ar,",1,",
                                 seasonal_ma,", curr_period:", 
                                 curr_period,", prediction length:" ,
                                 pred_len, " MAE", sep="")]], mae)
                }
              }
            }
          }
        }
      }
    }
  }
  mean_results = lapply(results, mean)
  print(mean_results[which.min(mean_results)])
  return(results)
}

# limit prediction lengths to long term (2nd longest).
etth1_gridsearch = grid_search_cv(etth1.ts, 0:2, 0:2, 1, periods=24, seasonal_ma_range=0:1,  
               seasonal_ar_range=0:0, pred_lens=c(336), n_folds=4, 
               non_oos_prop=0.8, first_year = 2016, first_val = first_hour_etth1, 
               dataset_freq = 24*365)

lapply(etth1_gridsearch, mean)[which.min(lapply(etth1_gridsearch, mean))]

etth2_gridsearch = grid_search_cv(etth2.ts, 0:2, 0:2, 1:2, periods=24, seasonal_ma_range=0:1,  
               seasonal_ar_range=0:0, pred_lens=336, n_folds=4, 
               non_oos_prop=0.8, first_year = 2016, first_val = first_hour_etth1, 
               dataset_freq = 24*365)

lapply(etth2_gridsearch, mean)[which.min(lapply(etth2_gridsearch, mean))]


# diff restricted to 0 -> 2 appears to flare up autocorrelations at lower lags.
ettm1_gridsearch = grid_search_cv(ettm1.ts, 0:2, 0:2, 0, periods=c(4,4*12), seasonal_ma_range=0:1,
               seasonal_ar_range=0:1, pred_lens=c(288), n_folds=4, 
               non_oos_prop=0.8, first_year = 2016, first_val = 4368, 
               dataset_freq = 24*365*4)

lapply(ettm1_gridsearch, mean)[which.min(lapply(ettm1_gridsearch, mean))]


weather_gridsearch = grid_search_cv(weather.ts, 0:1, 0:1, 0, periods=c(24), 
                                    seasonal_ma_range=0:1,
               seasonal_ar_range=0:1, pred_lens=c(336), n_folds=4, 
               non_oos_prop=0.8, first_year = 2010, first_val = 0, 
               dataset_freq = 24*365)

lapply(weather_gridsearch, mean)[which.min(lapply(weather_gridsearch, mean))]


aeph_gridsearch = grid_search_cv(aeph.ts, 0:2, 0:2, 0, periods=c(24*2), 
                                    seasonal_ma_range=0:1,
               seasonal_ar_range=0:1, pred_lens=288, n_folds=4, 
               non_oos_prop=0.8, first_year = 2004, first_val = first_hour_aeph, 
               dataset_freq = 24*365)

lapply(aeph_gridsearch, mean)[which.min(lapply(aeph_gridsearch, mean))]

# run on residuals 
etth1.residuals_gridsearch = grid_search_cv(etth1.ts.residuals, 0:2, 0:2, 1, periods=24, seasonal_ma_range=0:1,  
               seasonal_ar_range=0:0, pred_lens=c(336), n_folds=4, 
               non_oos_prop=0.8, first_year = 2016, first_val = first_hour_etth1, 
               dataset_freq = 24*365)

which.min(lapply(etth1.residuals_gridsearch, mean))

etth2.residuals_gridsearch = grid_search_cv(etth2.ts.residuals, 0:2, 0:2, 1, periods=24, seasonal_ma_range=0:1,  
               seasonal_ar_range=0:0, pred_lens=c(336), n_folds=4, 
               non_oos_prop=0.8, first_year = 2016, first_val = first_hour_etth1, 
               dataset_freq = 24*365)

which.min(lapply(etth2.residuals_gridsearch, mean))

ettm1.residuals_gridsearch = grid_search_cv(ettm1.ts.residuals, 0:2, 0:2, 0, periods=4*12, seasonal_ma_range=0:1,  
               seasonal_ar_range=0:0, pred_lens=c(288), n_folds=4, 
               non_oos_prop=0.8, first_year = 2016, first_val = 4368, 
               dataset_freq = 24*365*4)

lapply(ettm1.residuals_gridsearch, mean)[which.min(lapply(ettm1.residuals_gridsearch, mean))]

weather.residuals_gridsearch = grid_search_cv(weather.ts.residuals, 0:1, 0:1, 0, periods=c(24), 
                                    seasonal_ma_range=0:1,
               seasonal_ar_range=0:1, pred_lens=c(336), n_folds=4, 
               non_oos_prop=0.8, first_year = 2010, first_val = 0, 
               dataset_freq = 24*365)
which.min(lapply(weather.residuals_gridsearch, mean))
lapply(weather.residuals_gridsearch, mean)[which.min(lapply(weather.residuals_gridsearch, mean))]


aeph.residuals_gridsearch = grid_search_cv(aeph.ts.residuals, 0:1, 0:1, 0, periods=c(24*2), 
                                    seasonal_ma_range=0:1,
               seasonal_ar_range=0:1, pred_lens=c(288), n_folds=4, 
               non_oos_prop=0.8, first_year = 2004, first_val = first_hour_aeph, 
               dataset_freq = 24*365)

which.min(lapply(aeph.residuals_gridsearch, mean))
# lapply(aeph.residuals_gridsearch, mean)
lapply(aeph.residuals_gridsearch, mean)[which.min(lapply(aeph.residuals_gridsearch, mean))]

```


```{r}

# ETTh1: order = c(1,1,2), seasonal=list(order=c(0,1,1), period=24)
# ETTh2: order = c(2,1,1), seasonal=list(order=c(0,1,1), period=24)
# ETTm1: order = c(0,0,2), seasonal=list(order=c(0,1,1), period=24*2)
# Weather: order = c(0,0,2), seasonal=list(order=c(0,1,1), period=24)
# AEPh: order = c(2,0,2), seasonal=list(order=c(1,1,1), period=24*2)

# residuals: 
# ETTh1: order = c(2,1,1), seasonal=list(order=c(0,1,1), period=24)
# ETTh2: order = c(2,1,1), seasonal=list(order=c(0,1,1), period=24)
# ETTm1: order = c(0,0,2), seasonal=list(order=c(0,1,1), period=24*2)
# Weather: order = c(2,0,1), seasonal=list(order=c(0,1,1), period=24)
# AEPh: order = c(2,0,2), seasonal=list(order=c(1,1,1), period=24*2)

# Evaluation
# Coefficients from SARIMA may be close to extremes of the unit circle.
# Train/Validation/Test Split
get_evaluation_on_ts = function(input_ts=etth1.ts, original_input_ts=etth1.ts.original,
                                include_trend_seasonality=F,freq=24*365, 
                                first_year=2016, 
                                first_val=first_hour_etth1, test_first_year=2018,
                                test_first_val=784, ylabel="",
                                prediction_length = c(24, 48, 168, 336, 720),
                                order_params = c(1,1,2),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24)) {
  # get validation middle 0.2 next time
  train_prop = 0.8
  test_prop = 0.2
  train_size = (train_prop*length(input_ts))
  train = ts(input_ts[1:train_size], start=c(first_year, first_val), freq=freq)
  # train = ts(input_ts[1:train_size], start=c(2004, first_hour_aeph), freq=24*365)
  test_start = train_size+1
  # test = ts(input_ts[test_start:length(input_ts)], start=c(2017,25071), freq=24*365*4)
  # test = ts(input_ts[test_start:length(input_ts)], start=c(2013,1770), freq=24*365)
  test = ts(input_ts[test_start:length(input_ts)], 
            start=c(test_first_year,test_first_val), freq=freq)
  # evaluated_model1 = arima(train, order = c(1,2,2), seasonal=list(order=c(0,1,1), period=24))
  # evaluated_model1 = arima(train, order = c(0,1,2), seasonal=list(order=c(0,1,2), period=24))
  if (include_trend_seasonality) {
    time_var_train = time(train)
    reg1_ = lm(train~time_var_train+I(time_var_train^3))
    seasonality_data = train-predict.lm(reg1_)
    
    f1 = 1
    f2 = 3
    f3 = 12
    d = freq
    v1 = cos(2*base::pi*f1*(1:train_size)/d)
    v2 = sin(2*base::pi*f1*(1:train_size)/d)
    v3 = cos(2*base::pi*f2*(1:train_size)/d)
    v4 = sin(2*base::pi*f2*(1:train_size)/d)
    v5 = cos(2*base::pi*f3*(1:train_size)/d)
    v6 = sin(2*base::pi*f3*(1:train_size)/d)
    
    seasonal_fit_ = lm(seasonality_data ~ 1 + v1 + v2 + v3 + v4 + v5 + v6)

    processed_train = seasonality_data-seasonal_fit_$fitted
    # evaluated_model1 = arima(processed_train, order = c(1,1,2), seasonal=list(order=c(0,1,1), period=24))
    # evaluated_model1 = arima(processed_train, order = c(0,1,1), seasonal=list(order=c(0,1,1), period=24))
    # evaluated_model1 = arima(processed_train, order = c(2,1,1), seasonal=list(order=c(0,1,1), period=24))
    # evaluated_model1 = arima(processed_train, order=c(1,1,2), seasonal=list(order=c(1,1,1), period=4*12) )
    evaluated_model1 = arima(processed_train, order = order_params, seasonal=list(order=seasonal_order, period=seasonal_period))
  } else {
    evaluated_model1 = arima(train, order = order_params, seasonal=list(order=seasonal_order, period=seasonal_period))
  }
  
  
  # may add as a parameter
  res_lst = list()
  for (pred_len in prediction_length) {
    pred_call = predict(evaluated_model1, n.ahead=pred_len)
    curr_pred = pred_call$pred
    if (include_trend_seasonality) {
      reg1_preds = coef(reg1_)[[1]] + coef(reg1_)[[2]]*time(test)[1:pred_len] + coef(reg1_)[[3]]*(time(test)[1:pred_len]^3)

      v1 = cos(2*base::pi*f1*(test_start:(test_start+pred_len-1))/d)
      v2 = sin(2*base::pi*f1*(test_start:(test_start+pred_len-1))/d)
      v3 = cos(2*base::pi*f2*(test_start:(test_start+pred_len-1))/d)
      v4 = sin(2*base::pi*f2*(test_start:(test_start+pred_len-1))/d)
      v5 = cos(2*base::pi*f3*(test_start:(test_start+pred_len-1))/d)
      v6 = sin(2*base::pi*f3*(test_start:(test_start+pred_len-1))/d)
    
      seasonal_preds = coef(seasonal_fit_)[[1]]+coef(seasonal_fit_)[[2]]*v1+
                       coef(seasonal_fit_)[[3]]*v2+coef(seasonal_fit_)[[4]]*v3+
                       coef(seasonal_fit_)[[5]]*v4+coef(seasonal_fit_)[[6]]*v5+
                       coef(seasonal_fit_)[[7]]*v6
      curr_pred = curr_pred + reg1_preds+seasonal_preds
    }
    # curr_se = pred_call$se
    plot(1:pred_len, test[1:pred_len]*sd(original_input_ts)+mean(original_input_ts),type="l",xlab="Time Steps",
         ylab=ylabel)
    points(1:pred_len, curr_pred*sd(original_input_ts)+mean(original_input_ts),type="l",col="darkblue")
  }
  return()
}



# seasonality
get_evaluation_on_ts(etth1.ts,original_input_ts=etth1.ts.original,include_trend_seasonality=T,
                     first_year=2016, first_val=first_hour_etth1,
                     test_first_year=2018,
                     test_first_val=784,ylabel="Transformer Oil Temperature (Celsius)",
                     order_params = c(2,1,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24))

get_evaluation_on_ts(etth1.ts,original_input_ts=etth1.ts.original,include_trend_seasonality=F,
                     first_year=2016, first_val=first_hour_etth1,
                     test_first_year=2018,
                     test_first_val=784,ylabel="Transformer Oil Temperature (Celsius)",
                     order_params = c(2,1,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24))


get_evaluation_on_ts(etth2.ts,original_input_ts=etth2.ts.original,include_trend_seasonality=T,
                     first_year=2016, first_val=first_hour_etth1,
                     test_first_year=2018,
                     test_first_val=784,ylabel="Transformer Oil Temperature (Celsius)",
                     order_params = c(2,1,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24))

get_evaluation_on_ts(etth2.ts,original_input_ts=etth2.ts.original,include_trend_seasonality=F,
                     first_year=2016, first_val=first_hour_etth1,
                     test_first_year=2018,
                     test_first_val=784,ylabel="Transformer Oil Temperature (Celsius)",
                     order_params = c(2,1,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24))
###########
get_evaluation_on_ts(ettm1.ts,original_input_ts=ettm1.ts.original,include_trend_seasonality=T,
                     freq=24*365*4,
                     first_year=2016, first_val=first_hour_etth1,
                     test_first_year=2017,
                     test_first_val=25072,
                     ylabel="Transformer Oil Temperature (Celsius)",
                     prediction_length=c(24, 48, 96, 288, 672),
                     order_params = c(0,0,2),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(4*12))

get_evaluation_on_ts(ettm1.ts,original_input_ts=ettm1.ts.original,include_trend_seasonality=F,
                     freq=24*365*4,
                     first_year=2016, first_val=first_hour_etth1,
                     test_first_year=2017,
                     test_first_val=25072,
                     ylabel="Transformer Oil Temperature (Celsius)",
                     prediction_length=c(24, 48, 96, 288, 672),
                     order_params = c(0,0,2),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(4*12))
#####################
# get_evaluation_on_ts(weather.ts,original_input_ts=weather.ts.original, include_trend_seasonality=F,
#                      first_year=2010, first_val=0,
#                      test_first_year=2014, 
#                      test_first_val=25,
#                      ylabel="Wet Bulb Temperature (Celsius)",
#                      order_params = c(1,0,1),
#                                 seasonal_order=c(0,1,1),
#                                 seasonal_period=c(24))

get_evaluation_on_ts(weather.ts,original_input_ts=weather.ts.original, include_trend_seasonality=T,
                     first_year=2010, first_val=0,
                     test_first_year=2014, 
                     test_first_val=25,
                     ylabel="Wet Bulb Temperature (Celsius)",
                     order_params = c(1,0,1),
                                seasonal_order=c(1,1,1),
                                seasonal_period=c(24))

get_evaluation_on_ts(weather.ts,original_input_ts=weather.ts.original, include_trend_seasonality=F,
                     first_year=2010, first_val=0,
                     test_first_year=2014, 
                     test_first_val=25,
                     ylabel="Wet Bulb Temperature (Celsius)",
                     order_params = c(0,0,1),
                                seasonal_order=c(1,1,1),
                                seasonal_period=c(24))


get_evaluation_on_ts(aeph.ts,original_input_ts=aeph.ts.original, include_trend_seasonality=T,
                     first_year=2004, first_val=first_hour_aeph,
                     test_first_year=2016, 
                     test_first_val=658,
                     ylabel="Megawatt Energy Consumption",
                     prediction_length=c(24, 48, 96, 288, 672),
                     order_params = c(1,0,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24*2))

get_evaluation_on_ts(aeph.ts,original_input_ts=aeph.ts.original, include_trend_seasonality=F,
                     first_year=2004, first_val=first_hour_aeph,
                     test_first_year=2016, 
                     test_first_val=658,
                     ylabel="Megawatt Energy Consumption",
                     prediction_length=c(24, 48, 96, 288, 672),
                     order_params = c(1,0,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24*2))

```

```{r}
get_evaluation_on_ts2 = function(input_ts=etth1.ts, include_trend_seasonality=F, freq=24*365, prediction_lengths=c(24,48,168,336,720),
                                first_year=2016, first_val=first_hour_etth1, test_first_year=2018,
                                test_first_val=784, order_params = c(1,1,2), seasonal_order=c(0,1,1),
                                seasonal_period=24) {
  set.seed(101)
  train_prop = 0.8
  test_prop = 0.2
  train_size = (train_prop*length(input_ts))
  test_size = (test_prop*length(input_ts))
  res_lst = list()
  for (pred_len in prediction_lengths) {
    avg_mse = 0
    avg_mae = 0
    for (trial in 1:10){
      print(paste("Prediction Length:", pred_len, "Trial:", trial))
      offset = sample(0:(test_size-pred_len), size=1)
      train = ts(input_ts[1:train_size], start=c(first_year, first_val), freq=freq)
      
      test_start = train_size+1
      
      test = ts(input_ts[test_start:length(input_ts)], start=c(test_first_year, test_first_val), freq=freq)
      if (include_trend_seasonality) {
        time_var_train = time(train)
        reg1_ = lm(train~time_var_train+I(time_var_train^3))
        seasonality_data = train-predict.lm(reg1_)
        
        f1 = 1
        f2 = 3
        f3 = 12
        d = freq
        v1 = cos(2*base::pi*f1*((1+offset):(train_size+offset) )/d)
        v2 = sin(2*base::pi*f1*((1+offset):(train_size+offset) )/d)
        v3 = cos(2*base::pi*f2*((1+offset):(train_size+offset) )/d)
        v4 = sin(2*base::pi*f2*((1+offset):(train_size+offset) )/d)
        v5 = cos(2*base::pi*f3*((1+offset):(train_size+offset) )/d)
        v6 = sin(2*base::pi*f3*((1+offset):(train_size+offset) )/d)
        seasonal_fit_ = lm(seasonality_data ~ 1 + v1 + v2 + v3 + v4 + v5 + v6)
    
        processed_train = seasonality_data-seasonal_fit_$fitted
        evaluated_model1 = arima(processed_train, order = order_params, seasonal=list(order=seasonal_order, period=seasonal_period))
      } else {
        evaluated_model1 = arima(train, order = order_params, seasonal=list(order=seasonal_order, period=seasonal_period))
      }
      pred_call = predict(evaluated_model1, n.ahead=pred_len)
      curr_pred = pred_call$pred
      if (include_trend_seasonality) {
        reg1_preds = coef(reg1_)[[1]] + coef(reg1_)[[2]]*time(test)[(1+offset):(offset+pred_len)] + coef(reg1_)[[3]]*(time(test)[(1+offset):(offset+pred_len)]^3)
  
        v1 = cos(2*base::pi*f1*((test_start+offset):(test_start+offset+pred_len-1))/d)
        v2 = sin(2*base::pi*f1*((test_start+offset):(test_start+offset+pred_len-1))/d)
        v3 = cos(2*base::pi*f2*((test_start+offset):(test_start+offset+pred_len-1))/d)
        v4 = sin(2*base::pi*f2*((test_start+offset):(test_start+offset+pred_len-1))/d)
        v5 = cos(2*base::pi*f3*((test_start+offset):(test_start+offset+pred_len-1))/d)
        v6 = sin(2*base::pi*f3*((test_start+offset):(test_start+offset+pred_len-1))/d)
        seasonal_preds = coef(seasonal_fit_)[[1]]+coef(seasonal_fit_)[[2]]*v1+
                         coef(seasonal_fit_)[[3]]*v2+coef(seasonal_fit_)[[4]]*v3+
                         coef(seasonal_fit_)[[5]]*v4+coef(seasonal_fit_)[[6]]*v5+
                         coef(seasonal_fit_)[[7]]*v6
        curr_pred = curr_pred + reg1_preds+seasonal_preds
      }
      mse = mean( (test[(1+offset):(pred_len+offset)]-curr_pred)^2)
      mae = mean( abs(test[(1+offset):(pred_len+offset)]-curr_pred))
      avg_mse = avg_mse + mse
      avg_mae = avg_mae + mae
    }
    res_lst[paste("mse_",pred_len,sep="")] = avg_mse/10
    res_lst[paste("mae_",pred_len,sep="")] = avg_mae/10
  }
  return(res_lst)
}

get_evaluation_on_ts2(etth2.ts,include_trend_seasonality=T,
                     order_params = c(2,1,1), 
                     seasonal_order=c(0,1,1),
                     seasonal_period=24)
get_evaluation_on_ts2(etth1.ts,include_trend_seasonality=T,
                     order_params = c(2,1,1), 
                     seasonal_order=c(0,1,1),
                     seasonal_period=24)
get_evaluation_on_ts2(ettm1.ts,freq=24*365*4, 
                     prediction_lengths=c(24,48, 96, 288, 672),
                     first_year=2016, first_val=first_hour_etth1,
                     test_first_year=2017,
                     test_first_val=25072,
                     order_params = c(0,0,2),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(4*12))
weather_test1 = get_evaluation_on_ts2(weather.ts,include_trend_seasonality=F,
                     freq=24*365, 
                     prediction_lengths=c(24,48, 168, 336, 720),
                     first_year=2010, first_val=0,
                     test_first_year=2014,
                     test_first_val=25,
                     order_params = c(1,0,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24))
aeph_test1 = get_evaluation_on_ts2(aeph.ts,include_trend_seasonality=T, freq=24*365,
                     prediction_length=c(24, 48, 96, 288, 672),
                     first_year=2004, first_val=first_hour_aeph,
                     test_first_year=2016, 
                     test_first_val=658,
                     order_params = c(0,0,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24*2))

aeph_test2 = get_evaluation_on_ts2(aeph.ts,include_trend_seasonality=F, freq=24*365,
                     prediction_length=c(24, 48, 96, 288, 672),
                     first_year=2004, first_val=first_hour_aeph,
                     test_first_year=2016, 
                     test_first_val=658,
                     order_params = c(0,0,1),
                                seasonal_order=c(0,1,1),
                                seasonal_period=c(24*2))


# $mse_24
# [1] 1.006021
# 
# $mae_24
# [1] 0.8506603
# 
# $mse_48
# [1] 1.448223
# 
# $mae_48
# [1] 0.8933712
# 
# $mse_96
# [1] 1.34877
# 
# $mae_96
# [1] 0.9128821
# 
# $mse_288
# [1] 1.48443
# 
# $mae_288
# [1] 0.9567673
# 
# $mse_672
# [1] 0.9993955
# 
# $mae_672
# [1] 0.7968718


```





